config/routes.rb
Rails.application.routes.draw do
  root to: 'records#index'

  resources :records, except: [:show, :new]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
  validates :title, :amount, :date, presence: true
  validates :amount, numericality: true

  scope :debit, -> { where("amount < ?", 0).sum(:amount) }
  scope :credit, -> { where("amount >= ?", 0).sum(:amount) }
  scope :balance, -> { sum(:amount) }

  scope :belonging_to, -> (session_user_id) { where(session_user_id: session_user_id) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def session_user
    @session_user ||= session[:user_id] || generate_session_user_id
  end

  def generate_session_user_id
    session[:user_id] = SecureRandom.hex
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:update, :destroy]

  # GET /records
  # GET /records.json
  def index
    load_records
    @record = Record.new(date: Date.today)
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.belonging_to(session_user).new(record_params)

    respond_to do |format|
      if @result = @record.save
        load_records

        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
        format.js {}
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
        format.js { render json: @record.errors.full_messages, status: :unprocessable_entity }
        # format.js   {}
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        load_records

        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
        format.js {}
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
        format.js   { render json: @record.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    load_records

    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
      format.js {}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = load_records.find(params[:id])
    end

    def load_records
      @records = Record.belonging_to(session_user)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:title, :date, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Accounts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/records/_destroy_record_modal.html.erb
<!-- Trigger the modal with a button -->
<!-- <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#delete-confirm">Open Modal</button> -->

<!-- Modal -->
<div id="delete-confirm" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Confirm Delete</h4>
      </div>
      <div class="modal-body">
        <p>You are about to delete <b><i class="title"></i></b> record, this procedure is irreversible.</p>
        <p>Do you want to proceed?</p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Delete', '', method: :delete, remote: true, class: 'btn btn-danger', id: 'destroy-record' %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>

app/views/records/_edit_record.html.erb
<tr class="js-edit-record" id="<%= dom_id(record) %>" style="display: none">
  <td><%= text_field_tag :title, record.title %></td>
  <td><%= date_field_tag :date, record.date %></td>
  <td><%= number_field_tag :amount, record.amount %></td>
  <td>
    <%= form_for record, remote: true, html: {} do |f| %>
        <%= f.submit 'Update', class: "btn btn-default", id: 'update-record' %>
        <%= link_to 'Cancel', '', class: 'btn btn-danger', id: 'cancel-edit-record' %>
    <% end %>
  </td>
</tr>

app/views/records/_new_record_form.html.erb
<%= form_for record, html: { class: 'form-inline well' }, remote: true do |f| %>
    <div class="form-group">
      <%= f.date_field :date %>
    </div>

    <div class="form-group">
      <%= f.text_field :title, placeholder: 'Title' %>
    </div>

    <div class="form-group">
      <%= f.text_field :amount, type: :number, placeholder: 'Amount' %>
    </div>

    <%= f.submit 'Create Record', class: "btn btn-primary", id: "create-record-submit" %>
    <%= button_tag 'Cancel', type: :reset, class: 'btn btn-danger', id: 'cancel-create-record' %>
<% end %>

app/views/records/_record_row.html.erb
<% cache record do %>
  <tbody class="js-record" id="<%= dom_id(record) %>">
    <%= render 'show_record', record: record %>
    <%= render 'edit_record', record: record %>
  </tbody>
<% end %>

app/views/records/_show_record.html.erb
<tr class="js-show-record" id="<%= dom_id(record) %>">
  <td id="title"><%= record.title %></td>
  <td id="date"><%= record.date %></td>
  <td id="amount"><%= record.amount %></td>
  <td>
    <%= link_to 'Edit', edit_record_path(record), class: 'btn btn-default', id: 'edit-record' %>
    <%= link_to 'Destroy', record, method: :delete, remote: true, class: 'btn btn-danger', id: 'destroy-record-modal',
                data: { id: record.id, title: record.title, url: record_url(record) } %>
  </td>
</tr>

app/views/records/create.js.erb
// Javascript in Assets not working after Rendering Partial in js.erb
var record_partial = "<%= j render partial: 'record_row', locals: {record: @record } %>";

record = new App.Record($(record_partial));
record.renderShow();

$('#counts #js-credit').html("<%= @records.credit %>");
$('#counts #js-debit').html("<%= @records.debit %>");
$('#counts #js-balance').html("<%= @records.balance %>");

app/views/records/destroy.js.erb
$("#<%= dom_id(@record) %>.js-record").fadeOut("slow", function() {
  $(this).remove();
  i = App.Record.allRecords.indexOf(this.id);
  App.Record.allRecords.splice(i);
});

$('#counts #js-credit').html("<%= @records.credit %>");
$('#counts #js-debit').html("<%= @records.debit %>");
$('#counts #js-balance').html("<%= @records.balance %>");

app/views/records/index.html.erb
<div id="notice">
  <div class="container"></div>
  <%= notice %>
</div>

<h1>Records</h1>

<% cache @records do %>
  <div class="row" id="counts">
    <div class="col-md-4">
      <div class="panel panel-success">
        <div class="panel-heading">Credit</div>
        <div class="panel-body" id="js-credit"><%= @records.credit %></div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-danger">
        <div class="panel-heading">Debit</div>
        <div class="panel-body" id="js-debit"><%= @records.debit %></div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-primary">
        <div class="panel-heading">Balance</div>
        <div class="panel-body" id="js-balance"><%= @records.balance %></div>
      </div>
    </div>
  </div>
<% end %>

<%= render partial: 'new_record_form', locals: { record: @record } %>

<table id="records_table" class="table table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Amount</th>
      <th></th>
    </tr>
  </thead>

  <% @records.each do |record| %>
    <%= render partial: "record_row", locals: { record: record } %>
  <% end %>
</table>

<%= render partial: 'destroy_record_modal' %>

app/views/records/update.js.erb
console.log('update clicked');
var record_partial = "<%= j render partial: 'record_row', locals: { record: @record } %>";

record = new App.Record($(record_partial));
record.renderShow();

$('#counts #js-credit').html("<%= @records.credit %>");
$('#counts #js-debit').html("<%= @records.debit %>");
$('#counts #js-balance').html("<%= @records.balance %>");